import { Html, Head, Main, NextScript } from "next/document";

/**
 * Document-level markup only.
 *
 * Titles, descriptions, canonicals and social cards live in <Seo> so they can
 * differ per page — previously every page shared one hardcoded set here, so
 * Google saw the same title and description for the homepage, the privacy
 * policy and the terms. The og:image also pointed at /og-image.png, which was
 * never added to the repo; it's now generated by /api/og.
 */
export default function Document() {
  return (
    <Html lang="en">
      <Head>
        {/* Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600;700&family=Great+Vibes&family=Outfit:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />

        {/* Tints the phone browser chrome — matches the stone page background. */}
        <meta name="theme-color" content="#FAFAF9" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
